# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cbcad509518f038187d683245cfa8333b85c6bfe3f48eee1139bef929e6e9bdf9543ad79b5d298e1849236cc1aa75089a8d2ea6ef5c953dd7de52763077b6bd

test:
  secret_key_base: 5f7dd4aa526fd28293ce6816714a01a45169556d5518215698f47866a2839f641d11962633f1d440579786db4257d13d90249f87058bb39b7c082b547ba7d150

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
